exports.seed = async function (knex) {
  await knex("languages").del();

  await knex("languages").insert([
    { name: "English" },
    { name: "Spanish" },
    { name: "French" },
    { name: "Mandarin Chinese" },
    { name: "German" },
    { name: "Italian" },
    { name: "Japanese" },
    { name: "Portuguese" },
    { name: "Arabic" },
    { name: "Korean" },
    { name: "Turkish" },
    { name: "Swedish" },
    { name: "Dutch" },
    { name: "Polish" },
    { name: "Greek" },
    { name: "Hindi" },
    { name: "Persian (Farsi)" },
    { name: "Hebrew" },
    { name: "Vietnamese" },
    { name: "Danish" },
    { name: "Finnish" },
    { name: "Norwegian" },
    { name: "Czech" },
    { name: "Hungarian" },
    { name: "Ukrainian" },
    { name: "Slovak" },
    { name: "Bulgarian" },
    { name: "Romanian" },
    { name: "Russian" },
    { name: "Thai" },
    { name: "Indonesian" },
    { name: "Malayalam" },
    { name: "Tamil" },
    { name: "Malay" },
    { name: "Swahili" },
    { name: "Kannada" },
    { name: "Oriya (Odia)" },
    { name: "Telugu" },
    { name: "Tagalog (Filipino)" },
    { name: "Hausa" },
    { name: "Amharic" },
    { name: "Zulu" },
    { name: "Pashto" },
    { name: "Bengali" },
    { name: "Burmese" },
    { name: "Armenian" },
    { name: "Georgian" },
    { name: "Albanian" },
    { name: "Lithuanian" },
    { name: "Serbian" },
  ]);
};
