exports.seed = async function(knex) {
   
    await knex('interests').del();
  
    await knex('interests').insert([
      { name: 'Technology' },
      { name: 'Startups' },
      { name: 'Business' },
      { name: 'Marketing' },
      { name: 'Finance' },
      { name: 'Investments' },
      { name: 'Leadership' },
      { name: 'Management' },
      { name: 'Programming' },
      { name: 'Software Development' },
      { name: 'Artificial Intelligence' },
      { name: 'Machine Learning' },
      { name: 'Data Science' },
      { name: 'Big Data' },
      { name: 'Cybersecurity' },
      { name: 'Design' },
      { name: 'UX/UI' },
      { name: 'Graphic Design' },
      { name: 'Web Design' },
      { name: 'Freelance' },
      { name: 'Creative Writing' },
      { name: 'Literature' },
      { name: 'Poetry' },
      { name: 'Photography' },
      { name: 'Videography' },
      { name: 'Cinema' },
      { name: 'Theater' },
      { name: 'Music' },
      { name: 'Painting' },
      { name: 'Visual Arts' },
      { name: 'Sculpture' },
      { name: 'Fashion' },
      { name: 'Travel' },
      { name: 'Cooking' },
      { name: 'Gastronomy' },
      { name: 'Health' },
      { name: 'Fitness' },
      { name: 'Yoga' },
      { name: 'Meditation' },
      { name: 'Psychology' },
      { name: 'Self-Improvement' },
      { name: 'Education' },
      { name: 'Science' },
      { name: 'History' },
      { name: 'Philosophy' },
      { name: 'Politics' },
      { name: 'Ecology' },
      { name: 'Journalism' },
      { name: 'Mass Media' },
      { name: 'Social Media' },
      { name: 'PR' },
      { name: 'Advertising' },
      { name: 'E-commerce' },
      { name: 'Economics' },
      { name: 'Sociology' },
      { name: 'Anthropology' },
      { name: 'Biology' },
      { name: 'Chemistry' },
      { name: 'Physics' },
      { name: 'Astronomy' },
      { name: 'Mathematics' },
      { name: 'Engineering' },
      { name: 'Architecture' },
      { name: 'Urban Planning' },
      { name: 'Landscape Design' },
      { name: 'Philanthropy' },
      { name: 'Volunteering' },
      { name: 'Community Work' },
      { name: 'Political Science' },
      { name: 'Jurisprudence' },
      { name: 'Game Design' },
      { name: 'Video Games' },
      { name: 'Board Games' },
      { name: 'Handicraft' },
      { name: 'Knitting' },
      { name: 'Sewing' },
      { name: 'Gardening' },
      { name: 'Floristics' },
      { name: 'Animal Husbandry' },
      { name: 'Fishing' },
      { name: 'Hunting' },
      { name: 'Philately' },
      { name: 'Numismatics' },
      { name: 'Collecting' },
      { name: 'Cars' },
      { name: 'Motorcycles' },
      { name: 'Aviation' },
      { name: 'Space' },
      { name: 'Sports' },
      { name: 'Football (Soccer)' },
      { name: 'Basketball' },
      { name: 'Tennis' },
      { name: 'Running' },
      { name: 'Swimming' },
      { name: 'Cycling' },
      { name: 'Mountaineering' },
      { name: 'Kayaking' },
      { name: 'Nature Travel' },
      { name: 'Camping' },
    ]);
  };
  